### ISSUE TITLE
Franz - Newer versions

### ISSUE THREAD

**Issue by francescor82** [Atoms/rukruk#1]
Hello,

The "Franz" messaging app has newer versions; the latest one seems to be 4.0.4 now.
Is it possible to update the ebuild, please?

Thanks,
Francesco

**Comment by tibfulv** [comment]
The binary is now at 5.1.0. There are also sources, at 5.2.0-beta.4, at https://github.com/meetfranz/franz .

**Comment by Atoms** [comment]
can you open pls new issue? or even better PR, as i don't use gentoo anymore on daily basis i need to bring up VM for testing then

**Comment by tibfulv** [comment]
I wonder if Portage can be installed on another system. I've been toying with the idea of exchanging package managers to transform a system from rpm to Portage, say, or vice versa. After all, underneath the hood it's all just a question of moving files to appropriate locations and registering them in various databases. Sort of like alien on steroids.
