### ISSUE TITLE
Missing dependencies net-im/franz-bin

### ISSUE THREAD

**Issue by m4rcu5** [Atoms/rukruk#2]
Hi,

It seems that the franz-bin is missing dependencies. It was most notable on my system due to the missing `gnome-base/gconf` ebuild.

Maybe the following snippet of the arch PKGBUILD helps out here:
`depends=('alsa-lib' 'bash' 'desktop-file-utils' 'gconf' 'gtk2' 'libnotify' 'libxtst' 'nss' 'libxss')`

**Comment by Atoms** [comment]
yes, it can be, cause i have already installed lot's of stuff, and those can be missing, will try to update ebuild this week.
