### ISSUE TITLE
Google Play Music Desktop Player

### ISSUE THREAD

**Issue by Silent-Hunter** [Atoms/rukruk#3]
Version 4.1.1 is out now, Portage still reports 4.0.2 as the latest even though I see 4.0.5 here, just thought I'd let you know.

**Comment by Atoms** [comment]
4.1.1 version shows 4.0.5 packages, as reading from gitter:
> That is expected there was an issue with 4.1.1 Linux releases so I uploaded old releases to stop people raising issues for things. Long story 

so for now i'm not creating ebuild for 4.1.1, will wait for next release.

**Comment by Silent-Hunter** [comment]
Alrighty! Looking forward to the next release then, whenever that is! Want
me to post here when I see the next update?

**Comment by Atoms** [comment]
Version up to 4.2.0. enjoy
